spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://39.106.24.18:8084
  zipkin:
    base-url: http://39.106.24.18:9411

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://39.106.24.18:8761/eureka/,http://39.106.24.18:8861/eureka/,http://39.106.24.18:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
