spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://39.106.24.18:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.24.18:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
